# Generated by Django 2.0 on 2017-12-10 19:53

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arvore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('escola', models.CharField(max_length=200, verbose_name='Escola')),
                ('serie', models.CharField(choices=[('1º ano', '1º ano'), ('2º ano', '2º ano'), ('3º ano', '3º ano'), ('4º ano', '4º ano'), ('5º ano', '5º ano'), ('6º ano', '6º ano'), ('7º ano', '7º ano'), ('8º ano', '8º ano'), ('9º ano', '9º ano'), ('1ª série', '1º série'), ('2ª série', '2º série'), ('3ª série', '3º série')], default='-', max_length=200, verbose_name='Série')),
                ('cidade', models.CharField(max_length=200, verbose_name='Cidade')),
            ],
            options={
                'db_table': 'arvore',
            },
        ),
        migrations.CreateModel(
            name='Gource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('cor', colorfield.fields.ColorField(default='#000000', max_length=18, verbose_name='Cor de fundo')),
                ('fonte', models.PositiveIntegerField(verbose_name='Tamanho da fonte')),
            ],
            options={
                'db_table': 'gource',
            },
        ),
        migrations.CreateModel(
            name='Hierarquia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
