# Generated by Django 2.0 on 2017-12-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gource',
            name='elasticidade',
            field=models.DecimalField(decimal_places=1, default='0.5', max_digits=2, verbose_name='Elasticidade'),
        ),
    ]
